ci: add fast and slow testcases

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -269,43 +269,22 @@ jobs:
             - name: Build
               shell: bash -l {0}
               run: |
-                  cmake --build build --target finite-volume-advection-1d --parallel 1      &
                   cmake --build build --target finite-volume-advection-2d --parallel 1      &
                   cmake --build build --target finite-volume-linear-convection --parallel 1 &
                   cmake --build build --target finite-volume-burgers --parallel 1           &
                   wait
 
-
-            - name: MPI test finite-volume-advection-1d
+            - name: MPI test finite-volume-advection-2d-fast
               shell: bash -l {0}
               run: |
                   cd build
                   set -e  # Stop on first failure
-                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.2 --nfiles 20 --max_level 10
-                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.2 --nfiles 20 --max_level 10
-                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.2 --nfiles 20 --max_level 10
-                  mpiexec -n 4 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.2 --nfiles 20 --max_level 10
-                  mpiexec -n 8 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.2 --nfiles 20 --max_level 10
-                  mpiexec -n 9 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.2 --nfiles 20 --max_level 10
-                  ls
-                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_2_ite_ --start 1 --end 19
-                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_3_ite_ --start 1 --end 19
-                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_4_ite_ --start 1 --end 19
-                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_8_ite_ --start 1 --end 19
-                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_9_ite_ --start 1 --end 19
-
-
-            - name: MPI test finite-volume-advection-2d
-              shell: bash -l {0}
-              run: |
-                  cd build
-                  set -e  # Stop on first failure
-                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.2 --nfiles 20
-                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.2 --nfiles 20
-                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.2 --nfiles 20
-                  mpiexec -n 4 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.2 --nfiles 20
-                  mpiexec -n 8 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.2 --nfiles 20
-                  mpiexec -n 9 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.2 --nfiles 20
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 20 --max-level 8
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 20 --max-level 8
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 20 --max-level 8
+                  mpiexec -n 4 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 20 --max-level 8
+                  mpiexec -n 8 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 20 --max-level 8
+                  mpiexec -n 9 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 20 --max-level 8
                   ls
                   python ../python/compare.py FV_advection_2d_size_1_ite_ FV_advection_2d_size_2_ite_ --start 1 --end 19
                   python ../python/compare.py FV_advection_2d_size_1_ite_ FV_advection_2d_size_3_ite_ --start 1 --end 19
@@ -313,7 +292,66 @@ jobs:
                   python ../python/compare.py FV_advection_2d_size_1_ite_ FV_advection_2d_size_8_ite_ --start 1 --end 19
                   python ../python/compare.py FV_advection_2d_size_1_ite_ FV_advection_2d_size_9_ite_ --start 1 --end 19
 
-            - name: MPI test finite-volume-burgers
+
+            - name: MPI test finite-volume-burgers-fast
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.05 --nfiles 20 --max-level 6
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.05 --nfiles 20 --max-level 6
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.05 --nfiles 20 --max-level 6
+                  mpiexec -n 4 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.05 --nfiles 20 --max-level 6
+                  mpiexec -n 6 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.05 --nfiles 20 --max-level 6
+                  mpiexec -n 8 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.05 --nfiles 20 --max-level 6
+                  ls
+                  python ../python/compare.py burgers_2D_size_1_ite_ burgers_2D_size_2_ite_ --start 1 --end 19
+                  python ../python/compare.py burgers_2D_size_1_ite_ burgers_2D_size_3_ite_ --start 1 --end 19
+                  python ../python/compare.py burgers_2D_size_1_ite_ burgers_2D_size_4_ite_ --start 1 --end 19
+                  python ../python/compare.py burgers_2D_size_1_ite_ burgers_2D_size_6_ite_ --start 1 --end 19
+                  python ../python/compare.py burgers_2D_size_1_ite_ burgers_2D_size_8_ite_ --start 1 --end 19
+
+
+            - name: MPI test finite-volume-linear-convection-fast
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-linear-convection --Tf 0.1 --nfiles 20 --max-level 5
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-linear-convection --Tf 0.1 --nfiles 20 --max-level 5
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-linear-convection --Tf 0.1 --nfiles 20 --max-level 5
+                  mpiexec -n 4 ./demos/FiniteVolume/finite-volume-linear-convection --Tf 0.1 --nfiles 20 --max-level 5
+                  mpiexec -n 6 ./demos/FiniteVolume/finite-volume-linear-convection --Tf 0.1 --nfiles 20 --max-level 5
+                  mpiexec -n 8 ./demos/FiniteVolume/finite-volume-linear-convection --Tf 0.1 --nfiles 20 --max-level 5
+                  ls
+                  python ../python/compare.py linear_convection_2D_ite linear_convection_2D_ite --start 1 --end 19
+                  python ../python/compare.py linear_convection_2D_ite linear_convection_2D_ite --start 1 --end 19
+                  python ../python/compare.py linear_convection_2D_ite linear_convection_2D_ite --start 1 --end 19
+                  python ../python/compare.py linear_convection_2D_ite linear_convection_2D_ite --start 1 --end 19
+                  python ../python/compare.py linear_convection_2D_ite linear_convection_2D_ite --start 1 --end 19
+
+
+
+            - name: MPI test finite-volume-advection-2d-slow
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.5 --nfiles 20 --max-level 10
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.5 --nfiles 20 --max-level 10
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.5 --nfiles 20 --max-level 10
+                  mpiexec -n 4 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.5 --nfiles 20 --max-level 10
+                  mpiexec -n 8 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.5 --nfiles 20 --max-level 10
+                  mpiexec -n 9 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.5 --nfiles 20 --max-level 10
+                  ls
+                  python ../python/compare.py FV_advection_2d_size_1_ite_ FV_advection_2d_size_2_ite_ --start 1 --end 19
+                  python ../python/compare.py FV_advection_2d_size_1_ite_ FV_advection_2d_size_3_ite_ --start 1 --end 19
+                  python ../python/compare.py FV_advection_2d_size_1_ite_ FV_advection_2d_size_4_ite_ --start 1 --end 19
+                  python ../python/compare.py FV_advection_2d_size_1_ite_ FV_advection_2d_size_8_ite_ --start 1 --end 19
+                  python ../python/compare.py FV_advection_2d_size_1_ite_ FV_advection_2d_size_9_ite_ --start 1 --end 19
+
+
+            - name: MPI test finite-volume-burgers-slow
               shell: bash -l {0}
               run: |
                   cd build
@@ -332,7 +370,7 @@ jobs:
                   python ../python/compare.py burgers_2D_size_1_ite_ burgers_2D_size_8_ite_ --start 1 --end 19
 
 
-            - name: MPI test finite-volume-linear-convection
+            - name: MPI test finite-volume-linear-convection-slow
               shell: bash -l {0}
               run: |
                   cd build
