ci: compile in parallel

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -269,8 +269,31 @@ jobs:
             - name: Build
               shell: bash -l {0}
               run: |
-                  cmake --build build --target finite-volume-advection-2d --parallel 4
-                  cmake --build build --target finite-volume-burgers --parallel 4
+                  cmake --build build --target finite-volume-advection-1d --parallel 4 &
+                  cmake --build build --target finite-volume-advection-2d --parallel 4 &
+                  cmake --build build --target finite-volume-linear-convection --parallel 4 &
+                  cmake --build build --target finite-volume-burgers --parallel 4 &
+                  wait
+
+
+            - name: MPI test finite-volume-advection-1d
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.5 --nfiles 20 --max_level 10
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.5 --nfiles 20 --max_level 10
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.5 --nfiles 20 --max_level 10
+                  mpiexec -n 4 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.5 --nfiles 20 --max_level 10
+                  mpiexec -n 8 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.5 --nfiles 20 --max_level 10
+                  mpiexec -n 9 ./demos/FiniteVolume/finite-volume-advection-1d --Tf 0.5 --nfiles 20 --max_level 10
+                  ls
+                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_2_ite_ --start 1 --end 19
+                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_3_ite_ --start 1 --end 19
+                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_4_ite_ --start 1 --end 19
+                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_8_ite_ --start 1 --end 19
+                  python ../python/compare.py FV_advection_1d_size_1_ite_ FV_advection_1d_size_9_ite_ --start 1 --end 19
+
 
             - name: MPI test finite-volume-advection-2d
               shell: bash -l {0}
@@ -501,8 +524,9 @@ jobs:
             - name: Build
               shell: bash -l {0}
               run: |
-                  cmake --build build --target finite-volume-advection-2d
-                  cmake --build build --target finite-volume-burgers
+                  cmake --build build --target finite-volume-advection-2d &
+                  cmake --build build --target finite-volume-burgers &
+                  wait
 
             - name: test finite-volume-advection-2d
               shell: bash -l {0}
